version: "3"

services:
  backend:
    depends_on:
     - "database"
     - "graph"
    image: "openjdk:12.0"
    ports:
      - "8080:80"
    restart: "always"
    volumes:
      - "./backend:/application"
    working_dir: "/application"
  database:
    environment:
     - "MYSQL_DATABASE=application"
     - "MYSQL_ROOT_PASSWORD=root"
    image: "mariadb:10.3"
    restart: "always"
    volumes:
     - "./database/data:/var/lib/mysql"
  frontend:
    depends_on:
     - "backend"
    image: "nginx:1.17"
    ports:
      - "8000:80"
    restart: "always"
    volumes:
      - "./frontend:/var/www"
    working_dir: "/application"
  graph:
    image: "neo4j:3.5"
    ports:
     - "7474:7474"
    restart: "always"
    volumes:
     - "./graph/data:/data"

